// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyBSCazseVQNbQOye1mk3mPGEKxx9YHKk',
    appId: '1:1091510788655:web:00be96638f1773331fdcda',
    messagingSenderId: '1091510788655',
    projectId: 'cheer-22e6d',
    authDomain: 'cheer-22e6d.firebaseapp.com',
    storageBucket: 'cheer-22e6d.firebasestorage.app',
    measurementId: 'G-NQJEJ4XE82',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmp7Gm03izVzxU6KpPrmSDFIPrcO0Dh00',
    appId: '1:1091510788655:android:feac99f20c374ccf1fdcda',
    messagingSenderId: '1091510788655',
    projectId: 'cheer-22e6d',
    storageBucket: 'cheer-22e6d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDN6CoprNc7UfdjkuVog_Als6pnWQBOYsk',
    appId: '1:1091510788655:ios:ebc6c57f84c41afc1fdcda',
    messagingSenderId: '1091510788655',
    projectId: 'cheer-22e6d',
    storageBucket: 'cheer-22e6d.firebasestorage.app',
    iosBundleId: 'com.example.cheer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDN6CoprNc7UfdjkuVog_Als6pnWQBOYsk',
    appId: '1:1091510788655:ios:ebc6c57f84c41afc1fdcda',
    messagingSenderId: '1091510788655',
    projectId: 'cheer-22e6d',
    storageBucket: 'cheer-22e6d.firebasestorage.app',
    iosBundleId: 'com.example.cheer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyBSCazseVQNbQOye1mk3mPGEKxx9YHKk',
    appId: '1:1091510788655:web:a4c6fe13b03e38431fdcda',
    messagingSenderId: '1091510788655',
    projectId: 'cheer-22e6d',
    authDomain: 'cheer-22e6d.firebaseapp.com',
    storageBucket: 'cheer-22e6d.firebasestorage.app',
    measurementId: 'G-W1G50JMDF1',
  );
}
